replicaCount: 1

image:
  repository: marketplace.gcr.io/google/redis5
  pullPolicy: Always
  tag: latest
  pullSecrets: 

  
resources:
  requests:
    cpu: 70m
    memory: 200Mi
  limits:
    cpu: 125m
    memory: 256Mi

service:
  type: ClusterIP
