replicaCount: 1
global:
  image:
    pullSecrets:
    
image:
  repository: eu.gcr.io/jetstack-steve-judd/recommendationservice
  pullPolicy: IfNotPresent
  
resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi

service:
  type: ClusterIP
