{{- template "lib-chart.deployment" (list . "emailservice.deployment") -}}
{{- define "emailservice.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: emailservice
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - {{ template "lib-chart.container" (list . "emailservice.deployment.container") }}
{{- end -}}
{{- define "emailservice.deployment.container" }}
env:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
ports:
- containerPort: 8080
readinessProbe:
  periodSeconds: 5
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:8080"]
livenessProbe:
  periodSeconds: 5
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:8080"]
{{- end -}}