apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-install-webhook-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-install-webhook
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-hook-serviceaccount
      containers:
        - name: {{ .Chart.Name }}-install-webhook
          image: {{ .Values.deployment.helmHookImage }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
            - ash
            - /helm_hook.sh
            - install
          volumeMounts:
            - mountPath: "/data"
              name: webhook-data
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-env
          resources:
            {{- include "helm.webhook-resources" . | nindent 12 }}
          securityContext:
            {{- include "helm.webhook-securitycontext" . | nindent 12 }}
      volumes:
        - name: webhook-data
          configMap:
            name: {{ .Chart.Name }}-script
      restartPolicy: OnFailure
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-delete-webhook-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete, pre-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-delete-webhook
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-hook-serviceaccount
      containers:
        - name: {{ .Chart.Name }}-delete-webhook
          image: {{ .Values.deployment.helmHookImage }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
            - ash
            - /helm_hook.sh
            - delete
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-env
          resources:
            {{- include "helm.webhook-resources" . | nindent 12 }}
          securityContext:
            {{- include "helm.webhook-securitycontext" . | nindent 12 }}
      restartPolicy: OnFailure
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-upgrade-webhook-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-upgrade-webhook
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-hook-serviceaccount
      containers:
        - name: {{ .Chart.Name }}-upgrade-webhook
          image: {{ .Values.deployment.helmHookImage }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
            - ash
            - /helm_hook.sh
            - upgrade
          volumeMounts:
            - mountPath: "/data"
              name: webhook-data
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-env
          resources:
            {{- include "helm.webhook-resources" . | nindent 12 }}
          securityContext:
            {{- include "helm.webhook-securitycontext" . | nindent 12 }}
      volumes:
        - name: webhook-data
          configMap:
            name: {{ .Chart.Name }}-script
      restartPolicy: OnFailure
