apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-hook-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, pre-delete, pre-upgrade, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
rules:
- apiGroups: ["admissionregistration.k8s.io", "admissionregistration.k8s.io/v1beta1"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "delete", "update", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list"]
