apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-hook-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, pre-delete, pre-upgrade, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-hook-role
  apiGroup: rbac.authorization.k8s.io
