apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, pre-delete, pre-upgrade, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
