{{ define "webhooks.yaml.tpl" }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .context.Chart.Name }}-webhook
  labels:
    {{- include "helm.labels" .context | nindent 4 }}
webhooks:
  - name: {{ .context.Chart.Name }}-svc.{{ .context.Release.Namespace }}.svc
    {{- if .context.Values.deployment.failurePolicy }}
    failurePolicy: {{ .context.Values.deployment.failurePolicy }}
    {{- else }}
    failurePolicy: Fail
    {{- end }}
    clientConfig:
      service:
        name: {{ .context.Chart.Name }}-svc
        namespace: {{ .context.Release.Namespace }}
        path: /mutate
      caBundle: {{ .cert | b64enc | quote }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods", "deployments", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs"]
    sideEffects: None
    {{- if .context.Values.namespacedValidation }}
    {{- if .context.Values.namespacedValidation.enabled }}
    namespaceSelector:
      matchExpressions:
      - key: securesystemsengineering.connaisseur/webhook
    {{- if not .context.Values.namespacedValidation.mode}}
        operator: NotIn
        values:
          - ignore
    {{- else if eq .context.Values.namespacedValidation.mode "ignore"}}
        operator: NotIn
        values:
          - ignore
    {{- else if eq .context.Values.namespacedValidation.mode "validate"}}
        operator: In
        values:
          - validate
   {{- end }}
   {{- end }}
   {{- end }}
{{ end }}
