apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
{{- range $k, $v := .Values.deploy.labels }}
    {{ $k }}: {{ $v }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: hashicorp/http-echo
        args:
        - "-text={{ .Values.outputText }}"
        ports:
        - containerPort: 5678
        env:
        {{- range $k,$v := .Values.deploy.envVars }}
        {{- range $kk,$vv := $v }}
        - name: {{ $kk }}
          value: {{ $vv }}
        {{- end }}
        {{- else }}
          []
        {{- end }}