apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    echo/test: {{ .Values.service.testLabel }}
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: {{ .Values.appName }}