{{- /*
lib-chart.metadata creates a standard metadata header.
It creates a 'metadata:' section with name and labels.
*/ -}}
{{ define "lib-chart.metadata" -}}
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "common.labels.standard" . | indent 4 -}}
{{- end -}}