replicaCount: 1
global:
  image:
    pullSecrets:
    
image:
  repository: eu.gcr.io/jetstack-steve-judd/cartservice
  pullPolicy: IfNotPresent
  
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  type: ClusterIP
