replicaCount: 1
users: 10
global:
  image:
    pullSecrets:
    
image:
  repository: eu.gcr.io/jetstack-steve-judd/loadgenerator
  pullPolicy: IfNotPresent
  
resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
