{{- template "lib-chart.deployment" (list . "checkoutservice.deployment") -}}
{{- define "checkoutservice.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: checkoutservice
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - {{ template "lib-chart.container" (list . "checkoutservice.deployment.container") }}
{{- end -}}
{{- define "checkoutservice.deployment.container" }}
env:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
ports:
- containerPort: 5050
readinessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:5050"]
livenessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=:5050"]
{{- end -}}